services:
  ubuntu:
    build: ./
    tty: true
    working_dir: /src
    volumes:
      - .:/src
      - practice:/src/practice
    command: >
      sh -c "/src/mkproblem.sh &&
            tail -f /dev/null"
volumes:
  practice:
